# Mouse mode
set -g mouse on

# Change leader to Ctrl + Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Make the current window obvious
set -g window-status-current-style 'fg=black,bg=white,bold'

# Hide the right-hand status information
set -g status-right ''
